export default [
	{
		symbol: "NVDA",
		name: "Nvidia",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 1.9503347661,
	},
	{
		symbol: "META",
		name: "Meta Platforms",
		sector: "Communication Services",
		subIndustry: "Interactive Media & Services",
		change52Wk: 1.8043206277,
	},
	{
		symbol: "RCL",
		name: "Royal Caribbean Group",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 1.2939523871,
	},
	{
		symbol: "PHM",
		name: "PulteGroup",
		sector: "Consumer Discretionary",
		subIndustry: "Homebuilding",
		change52Wk: 1.2136069018,
	},
	{
		symbol: "CCL",
		name: "Carnival",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 1.2023669858,
	},
	{
		symbol: "AMD",
		name: "Advanced Micro Devices",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 1.1273503456,
	},
	{
		symbol: "CRM",
		name: "Salesforce",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 1.0394480189,
	},
	{
		symbol: "PANW",
		name: "Palo Alto Networks",
		sector: "Information Technology",
		subIndustry: "Systems Software",
		change52Wk: 1.0350992569,
	},
	{
		symbol: "GE",
		name: "General Electric",
		sector: "Industrials",
		subIndustry: "Industrial Conglomerates",
		change52Wk: 1.0329379434,
	},
	{
		symbol: "AVGO",
		name: "Broadcom Inc.",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 1.0322355144,
	},
	{
		symbol: "FICO",
		name: "Fair Isaac",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.9128388669,
	},
	{
		symbol: "ANET",
		name: "Arista Networks",
		sector: "Information Technology",
		subIndustry: "Communications Equipment",
		change52Wk: 0.9052239942,
	},
	{
		symbol: "BKNG",
		name: "Booking Holdings",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 0.7947022411,
	},
	{
		symbol: "NOW",
		name: "ServiceNow",
		sector: "Information Technology",
		subIndustry: "Systems Software",
		change52Wk: 0.7705200671,
	},
	{
		symbol: "LRCX",
		name: "Lam Research",
		sector: "Information Technology",
		subIndustry: "Semiconductor Materials & Equipment",
		change52Wk: 0.742431016,
	},
	{
		symbol: "ADBE",
		name: "Adobe Inc.",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.7270632065,
	},
	{
		symbol: "MPWR",
		name: "Monolithic Power Systems",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.7254992771,
	},
	{
		symbol: "BX",
		name: "Blackstone",
		sector: "Financials",
		subIndustry: "Asset Management & Custody Banks",
		change52Wk: 0.71601003,
	},
	{
		symbol: "INTC",
		name: "Intel",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.7147102421,
	},
	{
		symbol: "AMZN",
		name: "Amazon",
		sector: "Consumer Discretionary",
		subIndustry: "Broadline Retail",
		change52Wk: 0.7069201022,
	},
	{
		symbol: "SNPS",
		name: "Synopsys",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.6901738812,
	},
	{
		symbol: "TSLA",
		name: "Tesla, Inc.",
		sector: "Consumer Discretionary",
		subIndustry: "Automobile Manufacturers",
		change52Wk: 0.687412682,
	},
	{
		symbol: "DHI",
		name: "DR Horton",
		sector: "Consumer Discretionary",
		subIndustry: "Homebuilding",
		change52Wk: 0.6794585503,
	},
	{
		symbol: "CDNS",
		name: "Cadence Design Systems",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.663725454,
	},
	{
		symbol: "EXPE",
		name: "Expedia Group",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 0.6557787062,
	},
	{
		symbol: "FDX",
		name: "FedEx",
		sector: "Industrials",
		subIndustry: "Air Freight & Logistics",
		change52Wk: 0.6380736463,
	},
	{
		symbol: "ABNB",
		name: "Airbnb",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 0.6367087932,
	},
	{
		symbol: "PNR",
		name: "Pentair",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.6328269463,
	},
	{
		symbol: "TDG",
		name: "TransDigm Group",
		sector: "Industrials",
		subIndustry: "Aerospace & Defense",
		change52Wk: 0.6271111859,
	},
	{
		symbol: "NFLX",
		name: "Netflix",
		sector: "Communication Services",
		subIndustry: "Movies & Entertainment",
		change52Wk: 0.6238175895,
	},
	{
		symbol: "CPRT",
		name: "Copart",
		sector: "Industrials",
		subIndustry: "Diversified Support Services",
		change52Wk: 0.6198046147,
	},
	{
		symbol: "LEN",
		name: "Lennar",
		sector: "Consumer Discretionary",
		subIndustry: "Homebuilding",
		change52Wk: 0.6190889774,
	},
	{
		symbol: "URI",
		name: "United Rentals",
		sector: "Industrials",
		subIndustry: "Trading Companies & Distributors",
		change52Wk: 0.6173233415,
	},
	{
		symbol: "STX",
		name: "Seagate Technology",
		sector: "Information Technology",
		subIndustry: "Technology Hardware, Storage & Peripherals",
		change52Wk: 0.6167273557,
	},
	{
		symbol: "TTWO",
		name: "Take-Two Interactive",
		sector: "Communication Services",
		subIndustry: "Interactive Home Entertainment",
		change52Wk: 0.5899165696,
	},
	{
		symbol: "LLY",
		name: "Eli Lilly and Company",
		sector: "Health Care",
		subIndustry: "Pharmaceuticals",
		change52Wk: 0.5895739733,
	},
	{
		symbol: "PH",
		name: "Parker Hannifin",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.5874015962,
	},
	{
		symbol: "WDC",
		name: "Western Digital",
		sector: "Information Technology",
		subIndustry: "Technology Hardware, Storage & Peripherals",
		change52Wk: 0.5867250926,
	},
	{
		symbol: "WST",
		name: "West Pharmaceutical Services",
		sector: "Health Care",
		subIndustry: "Health Care Supplies",
		change52Wk: 0.5842547658,
	},
	{
		symbol: "INTU",
		name: "Intuit",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.5806275453,
	},
	{
		symbol: "NRG",
		name: "NRG Energy",
		sector: "Utilities",
		subIndustry: "Independent Power Producers & Energy Traders",
		change52Wk: 0.5703703549,
	},
	{
		symbol: "MU",
		name: "Micron Technology",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.5634723284,
	},
	{
		symbol: "CMG",
		name: "Chipotle Mexican Grill",
		sector: "Consumer Discretionary",
		subIndustry: "Restaurants",
		change52Wk: 0.5535561575,
	},
	{
		symbol: "AMAT",
		name: "Applied Materials",
		sector: "Information Technology",
		subIndustry: "Semiconductor Materials & Equipment",
		change52Wk: 0.546357221,
	},
	{
		symbol: "ETN",
		name: "Eaton Corporation",
		sector: "Industrials",
		subIndustry: "Electrical Components & Equipment",
		change52Wk: 0.5366343279,
	},
	{
		symbol: "FLT",
		name: "Fleetcor",
		sector: "Financials",
		subIndustry: "Transaction & Payment Processing Services",
		change52Wk: 0.5306482355,
	},
	{
		symbol: "LULU",
		name: "Lululemon Athletica",
		sector: "Consumer Discretionary",
		subIndustry: "Apparel, Accessories & Luxury Goods",
		change52Wk: 0.5298842186,
	},
	{
		symbol: "KLAC",
		name: "KLA Corporation",
		sector: "Information Technology",
		subIndustry: "Semiconductor Materials & Equipment",
		change52Wk: 0.5176894535,
	},
	{
		symbol: "MSFT",
		name: "Microsoft",
		sector: "Information Technology",
		subIndustry: "Systems Software",
		change52Wk: 0.5151007695,
	},
	{
		symbol: "AXON",
		name: "Axon Enterprise",
		sector: "Industrials",
		subIndustry: "Aerospace & Defense",
		change52Wk: 0.5116334077,
	},
	{
		symbol: "PWR",
		name: "Quanta Services",
		sector: "Industrials",
		subIndustry: "Construction & Engineering",
		change52Wk: 0.5008026653,
	},
	{
		symbol: "CE",
		name: "Celanese",
		sector: "Materials",
		subIndustry: "Specialty Chemicals",
		change52Wk: 0.4970944728,
	},
	{
		symbol: "GWW",
		name: "W. W. Grainger",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.4741608199,
	},
	{
		symbol: "NTAP",
		name: "NetApp",
		sector: "Information Technology",
		subIndustry: "Technology Hardware, Storage & Peripherals",
		change52Wk: 0.4741379081,
	},
	{
		symbol: "GOOG",
		name: "Alphabet Inc. (Class C)",
		sector: "Communication Services",
		subIndustry: "Interactive Media & Services",
		change52Wk: 0.4730353889,
	},
	{
		symbol: "PCAR",
		name: "Paccar",
		sector: "Industrials",
		subIndustry: "Construction Machinery & Heavy Transportation Equipment",
		change52Wk: 0.4697649016,
	},
	{
		symbol: "GOOGL",
		name: "Alphabet Inc. (Class A)",
		sector: "Communication Services",
		subIndustry: "Interactive Media & Services",
		change52Wk: 0.4690893304,
	},
	{
		symbol: "AAPL",
		name: "Apple Inc.",
		sector: "Information Technology",
		subIndustry: "Technology Hardware, Storage & Peripherals",
		change52Wk: 0.4688128421,
	},
	{
		symbol: "DVA",
		name: "DaVita Inc.",
		sector: "Health Care",
		subIndustry: "Health Care Services",
		change52Wk: 0.4596049868,
	},
	{
		symbol: "BR",
		name: "Broadridge Financial Solutions",
		sector: "Industrials",
		subIndustry: "Data Processing & Outsourced Services",
		change52Wk: 0.4529433156,
	},
	{
		symbol: "MAS",
		name: "Masco",
		sector: "Industrials",
		subIndustry: "Building Products",
		change52Wk: 0.4474905534,
	},
	{
		symbol: "IR",
		name: "Ingersoll Rand",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.4447875954,
	},
	{
		symbol: "COF",
		name: "Capital One",
		sector: "Financials",
		subIndustry: "Consumer Finance",
		change52Wk: 0.4392896212,
	},
	{
		symbol: "MAR",
		name: "Marriott International",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 0.437934905,
	},
	{
		symbol: "BA",
		name: "Boeing",
		sector: "Industrials",
		subIndustry: "Aerospace & Defense",
		change52Wk: 0.4308066777,
	},
	{
		symbol: "NVR",
		name: "NVR, Inc.",
		sector: "Consumer Discretionary",
		subIndustry: "Homebuilding",
		change52Wk: 0.4287586377,
	},
	{
		symbol: "COST",
		name: "Costco",
		sector: "Consumer Staples",
		subIndustry: "Consumer Staples Merchandise Retail",
		change52Wk: 0.4277169572,
	},
	{
		symbol: "NXPI",
		name: "NXP Semiconductors",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.4227338806,
	},
	{
		symbol: "NCLH",
		name: "Norwegian Cruise Line Holdings",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 0.4217877824,
	},
	{
		symbol: "AOS",
		name: "A. O. Smith",
		sector: "Industrials",
		subIndustry: "Building Products",
		change52Wk: 0.4130240504,
	},
	{
		symbol: "WELL",
		name: "Welltower",
		sector: "Real Estate",
		subIndustry: "Health Care REITs",
		change52Wk: 0.4115360906,
	},
	{
		symbol: "CBOE",
		name: "Cboe Global Markets",
		sector: "Financials",
		subIndustry: "Financial Exchanges & Data",
		change52Wk: 0.4113852445,
	},
	{
		symbol: "TT",
		name: "Trane Technologies",
		sector: "Industrials",
		subIndustry: "Building Products",
		change52Wk: 0.4083117945,
	},
	{
		symbol: "MLM",
		name: "Martin Marietta Materials",
		sector: "Materials",
		subIndustry: "Construction Materials",
		change52Wk: 0.4069840926,
	},
	{
		symbol: "AKAM",
		name: "Akamai",
		sector: "Information Technology",
		subIndustry: "Internet Services & Infrastructure",
		change52Wk: 0.4019768732,
	},
	{
		symbol: "HUBB",
		name: "Hubbell Incorporated",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.3986161377,
	},
	{
		symbol: "PTC",
		name: "PTC",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.3850700702,
	},
	{
		symbol: "HWM",
		name: "Howmet Aerospace",
		sector: "Industrials",
		subIndustry: "Aerospace & Defense",
		change52Wk: 0.3847363692,
	},
	{
		symbol: "GRMN",
		name: "Garmin",
		sector: "Consumer Discretionary",
		subIndustry: "Consumer Electronics",
		change52Wk: 0.3831559807,
	},
	{
		symbol: "MCO",
		name: "Moody's Corporation",
		sector: "Financials",
		subIndustry: "Financial Exchanges & Data",
		change52Wk: 0.3808205,
	},
	{
		symbol: "CARR",
		name: "Carrier Global",
		sector: "Industrials",
		subIndustry: "Building Products",
		change52Wk: 0.3731736966,
	},
	{
		symbol: "CTSH",
		name: "Cognizant",
		sector: "Information Technology",
		subIndustry: "IT Consulting & Other Services",
		change52Wk: 0.3709502571,
	},
	{
		symbol: "ECL",
		name: "Ecolab",
		sector: "Materials",
		subIndustry: "Specialty Chemicals",
		change52Wk: 0.3660534162,
	},
	{
		symbol: "ZTS",
		name: "Zoetis",
		sector: "Health Care",
		subIndustry: "Pharmaceuticals",
		change52Wk: 0.358784329,
	},
	{
		symbol: "NWS",
		name: "News Corp (Class B)",
		sector: "Communication Services",
		subIndustry: "Publishing",
		change52Wk: 0.3574986774,
	},
	{
		symbol: "GNRC",
		name: "Generac",
		sector: "Industrials",
		subIndustry: "Electrical Components & Equipment",
		change52Wk: 0.3541403285,
	},
	{
		symbol: "HLT",
		name: "Hilton Worldwide",
		sector: "Consumer Discretionary",
		subIndustry: "Hotels, Resorts & Cruise Lines",
		change52Wk: 0.3530039568,
	},
	{
		symbol: "GPN",
		name: "Global Payments",
		sector: "Financials",
		subIndustry: "Transaction & Payment Processing Services",
		change52Wk: 0.3523949602,
	},
	{
		symbol: "MPC",
		name: "Marathon Petroleum",
		sector: "Energy",
		subIndustry: "Oil & Gas Refining & Marketing",
		change52Wk: 0.3519818213,
	},
	{
		symbol: "FI",
		name: "Fiserv",
		sector: "Financials",
		subIndustry: "Transaction & Payment Processing Services",
		change52Wk: 0.3492594039,
	},
	{
		symbol: "VRTX",
		name: "Vertex Pharmaceuticals",
		sector: "Health Care",
		subIndustry: "Biotechnology",
		change52Wk: 0.347375358,
	},
	{
		symbol: "CEG",
		name: "Constellation Energy",
		sector: "Utilities",
		subIndustry: "Electric Utilities",
		change52Wk: 0.3463719287,
	},
	{
		symbol: "VRSK",
		name: "Verisk",
		sector: "Industrials",
		subIndustry: "Research & Consulting Services",
		change52Wk: 0.3427036582,
	},
	{
		symbol: "RL",
		name: "Ralph Lauren Corporation",
		sector: "Consumer Discretionary",
		subIndustry: "Apparel, Accessories & Luxury Goods",
		change52Wk: 0.3410344423,
	},
	{
		symbol: "LYV",
		name: "Live Nation Entertainment",
		sector: "Communication Services",
		subIndustry: "Movies & Entertainment",
		change52Wk: 0.34063711,
	},
	{
		symbol: "FAST",
		name: "Fastenal",
		sector: "Industrials",
		subIndustry: "Trading Companies & Distributors",
		change52Wk: 0.3402967431,
	},
	{
		symbol: "ODFL",
		name: "Old Dominion",
		sector: "Industrials",
		subIndustry: "Cargo Ground Transportation",
		change52Wk: 0.3329150206,
	},
	{
		symbol: "IDXX",
		name: "Idexx Laboratories",
		sector: "Health Care",
		subIndustry: "Health Care Equipment",
		change52Wk: 0.327095285,
	},
	{
		symbol: "GEHC",
		name: "GE HealthCare",
		sector: "Health Care",
		subIndustry: "Health Care Equipment",
		change52Wk: 0.3219950638,
	},
	{
		symbol: "AIZ",
		name: "Assurant",
		sector: "Financials",
		subIndustry: "Multi-line Insurance",
		change52Wk: 0.3209026829,
	},
	{
		symbol: "IRM",
		name: "Iron Mountain",
		sector: "Real Estate",
		subIndustry: "Other Specialized REITs",
		change52Wk: 0.3160239753,
	},
	{
		symbol: "IT",
		name: "Gartner",
		sector: "Information Technology",
		subIndustry: "IT Consulting & Other Services",
		change52Wk: 0.3141910748,
	},
	{
		symbol: "NWSA",
		name: "News Corp (Class A)",
		sector: "Communication Services",
		subIndustry: "Publishing",
		change52Wk: 0.3123948244,
	},
	{
		symbol: "ON",
		name: "ON Semiconductor",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.3100337278,
	},
	{
		symbol: "DLR",
		name: "Digital Realty",
		sector: "Real Estate",
		subIndustry: "Data Center REITs",
		change52Wk: 0.3016544906,
	},
	{
		symbol: "ACN",
		name: "Accenture",
		sector: "Information Technology",
		subIndustry: "IT Consulting & Other Services",
		change52Wk: 0.3012325303,
	},
	{
		symbol: "ORCL",
		name: "Oracle Corporation",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.2983161261,
	},
	{
		symbol: "NUE",
		name: "Nucor",
		sector: "Materials",
		subIndustry: "Steel",
		change52Wk: 0.29356287,
	},
	{
		symbol: "SWK",
		name: "Stanley Black & Decker",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.2924911599,
	},
	{
		symbol: "PSX",
		name: "Phillips 66",
		sector: "Energy",
		subIndustry: "Oil & Gas Refining & Marketing",
		change52Wk: 0.2904411358,
	},
	{
		symbol: "CMCSA",
		name: "Comcast",
		sector: "Communication Services",
		subIndustry: "Cable & Satellite",
		change52Wk: 0.2896490976,
	},
	{
		symbol: "SHW",
		name: "Sherwin-Williams",
		sector: "Materials",
		subIndustry: "Specialty Chemicals",
		change52Wk: 0.2881855842,
	},
	{
		symbol: "ALGN",
		name: "Align Technology",
		sector: "Health Care",
		subIndustry: "Health Care Supplies",
		change52Wk: 0.2865646833,
	},
	{
		symbol: "SPGI",
		name: "S&P Global",
		sector: "Financials",
		subIndustry: "Financial Exchanges & Data",
		change52Wk: 0.283215521,
	},
	{
		symbol: "TYL",
		name: "Tyler Technologies",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.2813613146,
	},
	{
		symbol: "DAL",
		name: "Delta Air Lines",
		sector: "Industrials",
		subIndustry: "Passenger Airlines",
		change52Wk: 0.2787677249,
	},
	{
		symbol: "APH",
		name: "Amphenol",
		sector: "Information Technology",
		subIndustry: "Electronic Components",
		change52Wk: 0.2783929191,
	},
	{
		symbol: "JPM",
		name: "JPMorgan Chase",
		sector: "Financials",
		subIndustry: "Diversified Banks",
		change52Wk: 0.2779797688,
	},
	{
		symbol: "ROP",
		name: "Roper Technologies",
		sector: "Information Technology",
		subIndustry: "Electronic Equipment & Instruments",
		change52Wk: 0.2761570518,
	},
	{
		symbol: "EFX",
		name: "Equifax",
		sector: "Industrials",
		subIndustry: "Research & Consulting Services",
		change52Wk: 0.2746222714,
	},
	{
		symbol: "MCHP",
		name: "Microchip Technology",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.2687491299,
	},
	{
		symbol: "SNA",
		name: "Snap-on",
		sector: "Industrials",
		subIndustry: "Industrial Machinery & Supplies & Components",
		change52Wk: 0.2682969929,
	},
	{
		symbol: "CAH",
		name: "Cardinal Health",
		sector: "Health Care",
		subIndustry: "Health Care Distributors",
		change52Wk: 0.2675327877,
	},
	{
		symbol: "VMC",
		name: "Vulcan Materials Company",
		sector: "Materials",
		subIndustry: "Construction Materials",
		change52Wk: 0.2662979535,
	},
	{
		symbol: "PKG",
		name: "Packaging Corporation of America",
		sector: "Materials",
		subIndustry: "Paper & Plastic Packaging Products & Materials",
		change52Wk: 0.2617551861,
	},
	{
		symbol: "ADSK",
		name: "Autodesk",
		sector: "Information Technology",
		subIndustry: "Application Software",
		change52Wk: 0.2593035394,
	},
	{
		symbol: "CTAS",
		name: "Cintas",
		sector: "Industrials",
		subIndustry: "Diversified Support Services",
		change52Wk: 0.2547386442,
	},
	{
		symbol: "POOL",
		name: "Pool Corporation",
		sector: "Consumer Discretionary",
		subIndustry: "Distributors",
		change52Wk: 0.2535940441,
	},
	{
		symbol: "BRO",
		name: "Brown & Brown",
		sector: "Financials",
		subIndustry: "Insurance Brokers",
		change52Wk: 0.2517117337,
	},
	{
		symbol: "QCOM",
		name: "Qualcomm",
		sector: "Information Technology",
		subIndustry: "Semiconductors",
		change52Wk: 0.2497162875,
	},
	{
		symbol: "V",
		name: "Visa Inc.",
		sector: "Financials",
		subIndustry: "Transaction & Payment Processing Services",
		change52Wk: 0.247184492,
	},
	{
		symbol: "CHTR",
		name: "Charter Communications",
		sector: "Communication Services",
		subIndustry: "Cable & Satellite",
		change52Wk: 0.2458355303,
	},
	{
		symbol: "SPG",
		name: "Simon Property Group",
		sector: "Real Estate",
		subIndustry: "Retail REITs",
		change52Wk: 0.2409732332,
	},
	{
		symbol: "WBD",
		name: "Warner Bros. Discovery",
		sector: "Communication Services",
		subIndustry: "Broadcasting",
		change52Wk: 0.23713425,
	},
	{
		symbol: "LIN",
		name: "Linde plc",
		sector: "Materials",
		subIndustry: "Industrial Gases",
		change52Wk: 0.235870518,
	},
	{
		symbol: "AXP",
		name: "American Express",
		sector: "Financials",
		subIndustry: "Consumer Finance",
		change52Wk: 0.2338345232,
	},
	{
		symbol: "STLD",
		name: "Steel Dynamics",
		sector: "Materials",
		subIndustry: "Steel",
		change52Wk: 0.2326272103,
	},
	{
		symbol: "RSG",
		name: "Republic Services",
		sector: "Industrials",
		subIndustry: "Environmental & Facilities Services",
		change52Wk: 0.2320790427,
	},
	{
		symbol: "FFIV",
		name: "F5, Inc.",
		sector: "Information Technology",
		subIndustry: "Communications Equipment",
		change52Wk: 0.2320177386,
	},
	{
		symbol: "CDW",
		name: "CDW",
		sector: "Information Technology",
		subIndustry: "Technology Distributors",
		change52Wk: 0.2314099582,
	},
	{
		symbol: "WAB",
		name: "Wabtec",
		sector: "Industrials",
		subIndustry: "Construction Machinery & Heavy Transportation Equipment",
		change52Wk: 0.2300252074,
	},
	{
		symbol: "MSI",
		name: "Motorola Solutions",
		sector: "Information Technology",
		subIndustry: "Communications Equipment",
		change52Wk: 0.2299952345,
	},
	{
		symbol: "CAT",
		name: "Caterpillar Inc.",
		sector: "Industrials",
		subIndustry: "Construction Machinery & Heavy Transportation Equipment",
		change52Wk: 0.2278273837,
	},
	{
		symbol: "ISRG",
		name: "Intuitive Surgical",
		sector: "Health Care",
		subIndustry: "Health Care Equipment",
		change52Wk: 0.2254421002,
	},
];
